
- name: Create Blank Security Groups
  ec2_group:
    name: "{{item.name}}"
    description: "{{item.description}}"
    vpc_id: "{{vpc_facts.id}}"
    region: "{{VpcRegion}}"
  with_items: "{{ security_groups }}"

- name: Populate Security Groups with rules
  ec2_group:
    name: "{{item.name}}"
    description: "{{item.description}}"
    vpc_id: "{{vpc_facts.id}}"
    region: "{{VpcRegion}}"
    rules: "{{item.ingress_rules}}"
    rules_egress: "{{item.egress_rules}}"
  with_items: "{{ security_groups }}"
